name: Mypy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
      
      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi --no-root

      - name: Install Mypy
        run: |
          poetry add mypy==1.14.0

      - name: Run Mypy
        run: |
          poetry run mypy -p hellsemble